(cl:in-package cubot-msg)
(cl:export '(IMUYAW-VAL
          IMUYAW
          WHEELSPEED0-VAL
          WHEELSPEED0
          WHEELSPEED1-VAL
          WHEELSPEED1
          WHEELSPEED2-VAL
          WHEELSPEED2
          WHEELSPEED3-VAL
          WHEELSPEED3
          STM32CLOCK-VAL
          STM32CLOCK
          GYROX-VAL
          GYROX
          GYROY-VAL
          GYROY
          GYROZ-VAL
          GYROZ
          ACCX-VAL
          ACCX
          ACCY-VAL
          ACCY
          ACCZ-VAL
          ACCZ
          QYAW-VAL
          QYAW
          QPITCH-VAL
          QPITCH
          QROLL-VAL
          QROLL
))